# Generated by Django 5.2.5 on 2025-08-23 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_first_name_alter_member_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='يرجى إدخال اسم عربي صحيح بدون مسافات.', regex='^[\\u0600-\\u06FF]+$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='fourth_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='يرجى إدخال اسم عربي صحيح بدون مسافات.', regex='^[\\u0600-\\u06FF]+$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='يرجى إدخال اسم عربي صحيح بدون مسافات.', regex='^[\\u0600-\\u06FF]+$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='third_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='يرجى إدخال اسم عربي صحيح بدون مسافات.', regex='^[\\u0600-\\u06FF]+$')]),
        ),
    ]
