# Generated by Django 5.2.5 on 2025-08-23 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_member_first_name_alter_member_fourth_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydepartment',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_head', to='core.moderator'),
        ),
        migrations.AlterField(
            model_name='activitydepartment',
            name='second_in_command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_head', to='core.moderator'),
        ),
    ]
