# Generated by Django 5.2.5 on 2025-08-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_default_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydepartment',
            name='dep_heading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
