# Generated by Django 5.2.5 on 2025-08-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_setup_db_consts'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
