# Generated by Django 5.2.5 on 2025-08-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_member_otp_code_member_otp_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='member',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
