# Generated by Django 5.2.5 on 2025-08-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_member_date_of_birth_member_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
