# Generated by Django 5.2.5 on 2025-08-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_member_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='score',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
