# Generated by Django 5.2.5 on 2025-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_achievement_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='ach_image',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='stage',
            field=models.CharField(choices=[('1', 'الأولى'), ('2', 'الثانية'), ('3', 'الثالثة'), ('4', 'الرابعة')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='studying_department',
            field=models.CharField(choices=[('C', 'علوم الحاسوب'), ('I', 'نظم المعلومات'), ('S', 'الأمن السيبراني'), ('D', 'الأنظمة الطبية الذكية')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='studying_shift',
            field=models.CharField(choices=[('A', 'صباحي'), ('P', 'مسائي')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
